services:
  app:
    build: .
    container_name: sensei_bot
    restart: unless-stopped
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/infra/storage/ega:/app/src/infra/storage/ega
    networks:
      - sensei_network

  mongodb:
    image: dockerhub.timeweb.cloud/library/mongo:6-jammy
    container_name: sensei_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB:-sensei}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "27017:27017"
    networks:
      - sensei_network

volumes:
  mongodb_data:

networks:
  sensei_network:
    driver: bridge