"""add_katana_fields

Revision ID: 7fb7e2948a01
Revises: 001_initial
Create Date: 2025-12-25 17:19:47.872763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7fb7e2948a01'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('katana_length', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('users', sa.Column('last_katana_up', sa.DateTime(timezone=True), nullable=True))  
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_katana_up')
    op.drop_column('users', 'katana_length')
    # ### end Alembic commands ###