"""add_boss_stats

Revision ID: a1b2c3d4e5f8
Revises: f6a7b8c9d0e1
Create Date: 2026-01-24 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1b2c3d4e5f8'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('boss_kills', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_boss_damage', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_boss_damage')
    op.drop_column('users', 'boss_kills')
    # ### end Alembic commands ###
